### PR TITLE
Update README showing more available functionnalities

### PR DESCRIPTION
**Pull request by marinang**
See #12

### CODE REVIEW

**Comment by eduardo-rodrigues** [comment]
Seems you closed this by mistake … ;-)

**Comment by marinang** [comment]
No I didn't It has element from the PR #13

**Comment by eduardo-rodrigues** [comment]
Sorry, seems I'm reacting too quickly. Ping me when things are ready in the various places … ;-)

**Comment by marinang** [comment]
No it's seems better to make another PR, I'm closing this one.

**Pull request closed without merging**
