### PR TITLE
Python 2.6 support removed

### PR DESCRIPTION
**Pull request by eduardo-rodrigues**

### CODE REVIEW

**Comment by eduardo-rodrigues** [comment]
Travis is failing and the cause may be a lack of memory. @ndawe, do you happen to know if this issue is easy to get sorted somehow? @henryiii, any idea? Thanks a lot.

**Comment by henryiii** [comment]
I'm having an issue with travis ATM too, it's not picking up a new commit. They might be having issues. I'd wait 1-2 days and see if there's a service broadcast. If it was working before, I don't see a reason it should fail now.

**Comment by henryiii** [comment]
When was the last time it built successfully?

**Comment by eduardo-rodrigues** [comment]
There were no Travis builds before a commit back in July just before this PR (see https://github.com/scikit-hep/numpythia/pull/3). So nothing to compare to, unfortunately. I just bumped into this long-standing PR again, and thought it's time to try and get it sorted.

**Comment by eduardo-rodrigues** [comment]
OK, this PR is anyway harmless and the build errors with some of the Python versions are unrelated. Merging this and the issue will be sorted by cleaning-up some things and moving to pytest.

**Pull request merged**
