### PR TITLE
Version 1.2.0 for Pythia 8.244

### PR DESCRIPTION
**Pull request by eduardo-rodrigues**
Work in progress ...

### CODE REVIEW

**Comment by eduardo-rodrigues** [comment]
OK, @henryiii, this was more painful than I imagined but we now have a version with the latest Pythia 8.2 series. At a later stage it will be good to produce another release with the latest 8.3 ...

Have a look if you spot anything special. Otherwise this is ready for merging and a subsequent tag as 1.2.0.

Thanks.

**Comment by henryiii** [comment]
You only changed 330 files...

**Comment by henryiii** [comment]
It would be nice to not store all of Pythia here, but unless there's a hidden git repo somewhere, probably the best we can do. The changes that I can see look fine.

**Comment by eduardo-rodrigues** [comment]
Yep, only ;-). No way out since it is a replacement of Pythia.

**Comment by marinang** [comment]
There is a Gitlab Repo of Pythia https://gitlab.com/Pythia8.

**Comment by eduardo-rodrigues** [comment]
Thanks @marinang. No idea how to make use of it to avoid having the copy of a large fraction of Pythia here. Something to work out in the future ...

**Pull request merged**
