### PR TITLE
add new observables in array representation of GenParticle

### PR DESCRIPTION
**Pull request by marinang**
Addition of pT, rap(idity), eta, phi, and theta to the array representation of a GenParticle.

### CODE REVIEW

**Comment by henryiii** [comment]
Can you rebase your branch on master, please? Testing was broken.

**Comment by eduardo-rodrigues** [comment]
Just a quick question, as I did not check: is the documentation up-to-date for this extension or shall it ask for an update of the README?

**Comment by marinang** [comment]
The doc is up to date yes.

**Comment by eduardo-rodrigues** [comment]
OK, so this ca be merged. Thanks!

**Comment by eduardo-rodrigues** [comment]
FYI @henryiii has ideas on how to deal more easily with updates to Cython, and noticed you are using an older version in this MR. We will still merge this and a new PR will try and improve matters.

**Pull request merged**
