### PR TITLE
Remove private copy of six package and rather use external version

### PR DESCRIPTION
**Pull request by eduardo-rodrigues**
As per our discussion @henryiii.

### CODE REVIEW

**Comment by henryiii** [comment]
You'll need to remove `'numpythia.extern',` from the setup.py main function, too. This is one of the reasons listing them there manually is a bad idea...

**Comment by eduardo-rodrigues** [comment]
Yep, noticed it and remove it - had indeed overlooked, not seeing it when grep'ing for 'six' somehow.

**Comment by eduardo-rodrigues** [comment]
Hi @henryiii, the issue is that same as the one we talked about yesterday. It's got to do with a mix-up when unittest tries to run. Will you have time to make the move to pytest as you suggested?

**Comment by henryiii** [comment]
Yes, later today. Would you like me to work on this branch or a new one and then you can merge this one?

**Comment by eduardo-rodrigues** [comment]
Brilliant!
As you prefer … We can even change the PR title to incorporate both things.

**Comment by henryiii** [comment]
Okay, I'll work here then.

**Pull request merged**
